service: aws-lambda-saml-authorizer

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1

package:
  include:
    - node_modules/**

functions:
  postSaml:
    handler: postSaml.handler
    events:
      - http:
          method: post
          path: saml
          cors: true